### ISSUE TITLE
python bindings

### ISSUE THREAD

**Issue by stites** [stites/CSSR#21]

**Comment by szhan** [comment]
Hi @stites, Is this package still under development? I am interested in using this in my research. Please let me know. Thanks.

**Comment by stites** [comment]
Heads up, I moved this thread to #22

**Comment by stites** [comment]
@szhan also, I just took a look at your fork with the R-bindings. Very cool! It looks like you made this fork against the C bindings which is the original algorithm. The looping-tree based version is computationally more efficient and more correct. If you want to experiment with this you should check out the CLI instructions at https://github.com/stites/CSSR#preview-v020 . If you would like to use multi-character symbols you should look the latest jar at https://github.com/stites/CSSR/releases/tag/v0.2.0-RC1-SNAPSHOT

**Comment by szhan** [comment]
Hi @stites, Thanks! I have actually worked with a student of Jim Crutchfield (Cosma's former PhD advisor, I think) on getting the old CSSR to work. The R-binding came out of that, but we got stuck dealing with some of the computational issues of the old CSSR. I would be quite interested in continuing this work.

Would you like some help on pushing this forward? If there is some basic work you do not have time for, I could be your guy. I do not use Scala though, just Python and R mostly. Please let me know. Thank.

**Comment by stites** [comment]
There isn't too much to do at the moment for "CSSR Phase Two" (who's work-in-progress title is "ROCS") just tests and benchmarking, but most of the initial work on that front is all in Scala. We should talk about what your requirements are: if you are close to publication -- I can rekindle the publication work for citation, if you are looking to beta-test the next version -- it's already available and having real use-cases would be nice, if you want to push work on the old CSSR -- yes! please submit a PR to the C++ folder and I can make another minor release. 

I've opened up a gitter channel at https://gitter.im/CSSR-lobby/Lobby (it's like slack, but is tied to github). I'm on there pretty frequently because of the datahaskell community. We can talk a bit faster there without losing chat history.
