### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by stites** [stites/CSSR#22]
RE: #21 

Hi @szhan. CSSR is not currently under development. The next version is code-complete, but a new job pulled me away from finishing final benchmarks and comparative parts, Cosma's sabbatical wrapped up, and Kristi changed roles at work -- so there is no paper to formalize this repo. I do make time to work on the codebase, but I almost exclusively work in haskell so I've been slowly (very slowly) refactoring the haskell folder to make parity with the scala side. I'm slowly wrapping up my current project and have been considering having another go at the final codebase+paper for 2018.

Every now and then Cosma and Kristi redirect emails to me and I help people out with the new code base (via email or video chat) and/or to update code according to requests. I consider CSSR to be a primary interest of mine, you can expect a decent response time on issues/email, but I'm not an expert in causal statistics so questions regarding theory and/or proofs will have to be directed directly to Kristi/Cosma.

Hope this helps. Let me know if I missed anything, if you have any questions, or if you have a request. You can also contact me at `sam at stites dot io`

**Comment by szhan** [comment]
Hi @stites, Thanks! I have actually worked with a student of Jim Crutchfield (Cosma's former PhD advisor, I think) on getting the old CSSR to work. The R-binding came out of that, but we got stuck dealing with some of the computational issues of the old CSSR. I would be quite interested in continuing this work.

Would you like some help on pushing this forward? If there is some basic work you do not have time for, I could be your guy. I do not use Scala though, just Python and R mostly. Please let me know. Thank.

**Comment by stites** [comment]
(Moving this from #21 -- I thought you posted your comment there):

There isn't too much to do at the moment for "CSSR Phase Two" (the work-in-progress title is "ROCS") just tests and benchmarking, but most of the initial work on that front is all in Scala. We should talk about what your requirements are: if you are close to publication -- I can rekindle the publication work for citation, if you are looking to beta-test the next version -- it's already available and having real use-cases would be nice, if you want to push work on the old CSSR -- yes! please submit a PR to the C++ folder and I can bump the v0.1.* releases. 

I've opened up a gitter channel at https://gitter.im/CSSR-lobby/Lobby (it's like slack, but is tied to github). I'm on there pretty frequently because of the datahaskell community. We can talk a bit faster there without losing chat history.
