### ISSUE TITLE
An example

### ISSUE THREAD

**Issue by Ellie785** [stites/CSSR#24]
Hi, can you provide an example on how to set up the commands in command line in order to run the program?

Thanks

**Comment by stites** [comment]
Hi @Ellie785 -- this repository is currently unmaintained and there are several versions of the code (which I am going to clean up now). Are you interested in the original CSSR algorithm, documented here: http://www.bactra.org/CSSR ?

If so, please build the source in `cpp` (you can document in #23 if you have trouble), generate a stream from https://github.com/stites/test-machines/tree/master/perl, and your binary should include the necessary command-line arguments. Usage can be found here: https://github.com/stites/CSSR/tree/master/cpp#usage

If you are interested in scala code, which was left with some unfinished theory, usage is here: https://github.com/stites/CSSR#preview-v020. Given the state of this repository, I'm going to roll back this repo to v0.1.0 which might break these links -- I imagine most people are not expecting to see the incomplete work.
